### ISSUE TITLE
conda run vntyper cohort fails with "KeyError: 'Confidence'"

### ISSUE THREAD

**Issue by holtgrewe** [hassansaei/VNtyper#51]
I called `conda run vntyper cohort` and the bottom of the trace looks as follows. I'd appreciate any help. I'm running alpha.25.

```
Traceback (most recent call last):
  File "/opt/conda/envs/vntyper/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Confidence'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/vntyper/bin/vntyper", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/vntyper/lib/python3.9/site-packages/vntyper/cli.py", line 596, in main
    aggregate_cohort(
  File "/opt/conda/envs/vntyper/lib/python3.9/site-packages/vntyper/scripts/cohort_summary.py", line 560, in aggregate_cohort
    generate_cohort_summary_report(
  File "/opt/conda/envs/vntyper/lib/python3.9/site-packages/vntyper/scripts/cohort_summary.py", line 406, in generate_cohort_summary_report
    kestrel_positive = len(kestrel_df[kestrel_df['Confidence'].str.contains('Low_Precision|High_Precision', na=False)])
  File "/opt/conda/envs/vntyper/lib/python3.9/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/opt/conda/envs/vntyper/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'Confidence'
```

**Comment by holtgrewe** [comment]
This is probably an issue with kestrel files being empty or so. I get the following in kestrel logs

```
10:08:36 [KestrelRunner] ERROR e.g.kestrel.runner.KestrelRunner - Error reading reference sequence(s): Error reading reference sequence: IO error reading sequence source MUC1-VNTR.fa (type auto): reference/MUC1-VNTR.fa (No such file or directory) (FileNotFoundException) (IOException)
```

**Comment by holtgrewe** [comment]
Ah, configuration has changed...

**Comment by holtgrewe** [comment]
Still, it would be nice if the cohort tool would be better at validating its input.
